const items =[ {
    id:'001',
    image: 'images/main/1.jpg',
    company: 'Carlton London',
    item_name: 'Rhodium-plated Cz floral studs',
    current_price: 606,
    original_price: 1045,
    discount_percentage: 42,
    return_period :14,
    delivery_date: '08 Nov 2023',
    rating: {
        stars: 4.5,
        count: 1400,
    },

},
{
    id: '002',
    image: 'images/main/2.jpg',
    company: 'CUKOO',
    item_name: 'Women Padded Halter Neck Swimming Dress',
    original_price: 2599,
    current_price: 1507,
    discount_percentage: 42,
    return_period: 14,
    delivery_date: '08 Nov 2023',
    rating: {
        stars: 4.3,
        count: 24,
    },
},
{
    id: '003',
    image:  'images/main/3.jpg',
    company: 'NUEVOSDAMAS',
    item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
    original_price: 1599,
    current_price: 495,
    discount_percentage: 69,
    return_period: 14,
    delivery_date: '08 Nov 2023',
    rating: {
        stars: 4.1,
        count: 249,
    },
},
{
    id: '004',
    image:  'images/main/4.jpg',
    company: 'ADIDAS',
    item_name: 'Indian Cricket ODI Jersey',
    original_price: 999,
    current_price: 999,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: '08 Nov 2023',
    rating: {
        stars: 5.0,
        count: 10,
    },
},
{
    id: '005',
    image:  'images/main/5.jpg',
    company: 'Roadster',
    item_name: 'Pure Cotton T-shirt',
    original_price: 1399,
    current_price: 489,
    discount_percentage: 65,
    return_period: 14,
    delivery_date: '08 Nov 2023',
    rating: {
        stars: 4.2,
        count: 3500,
    },
},
{
    id: '006',
    image:  'images/main/6.jpg',
    company: 'Nike',
    item_name: 'Men ReactX Running Shoes',
    original_price: 14995,
    current_price: 14995,
    discount_percentage: 0,
    return_period: 14,
    delivery_date: '08 Nov 2023',
    rating: {
        stars: 0.0,
        count: 0,
    },
},
{
    id: '007',
    image:  'images/main/7.jpg',
    company: 'The Indian Garage Co',
    item_name: 'Men Slim Fit Regular Shorts',
    original_price: 1599,
    current_price: 639,
    discount_percentage: 60,
    return_period: 14,
    delivery_date: '08 Nov 2023',
    rating: {
        stars: 4.2,
        count: 388,
    },
},
{
    id: '008',
    image:  'images/main/8.jpg',
    company: 'Nivea',
    item_name: 'Men Fresh Deodrant 150ml',
    original_price: 285,
    current_price: 142,
    discount_percentage: 50,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.2,
        count: 5200,
    },
},

{
    id: '009',
    image:  'images/offers/2.png',
    company: 'Calvin Klein',
    item_name: 'Down Shoulder T-shirt',
    original_price: 900,
    current_price: 450,
    discount_percentage: 50,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 3.5,
        count: 595,
    },
},
{
    id: '10',
    image:  'images/offers/1.png',
    company: 'Trend',
    item_name: 'Trend formal Collection',
    original_price: 500,
    current_price: 300,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.2,
        count: 3089,
    },
},
{
    id: '11',
    image:  'images/offers/3.png',
    company: 'ALDO',
    item_name: 'ALDO Black & Golden',
    original_price: 1000,
    current_price: 600,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 3.2,
        count: 2099,
    },
},
{
    id: '12',
    image:  'images/offers/4.png',
    company: 'Max Fashion',
    item_name: 'Max Black & Orange Jacket',
    original_price: 1500,
    current_price: 900,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.5,
        count: 2518,
    },
},
{
    id: '13',
    image:  'images/offers/5.png',
    company: 'Nautica',
    item_name: 'Loyal Collection Shirt',
    original_price: 5000,
    current_price: 2500,
    discount_percentage: 50,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.2,
        count: 1089,
    },
},
{
    id: '14',
    image:  'images/offers/6.png',
    company: 'Dorothy Perkins',
    item_name: 'Skin  trip hill',
    original_price: 1200,
    current_price: 840,
    discount_percentage: 30,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 3.2,
        count: 2789,
    },
},
{
    id: '15',
    image:  'images/offers/7.png',
    company: 'Jack & Jones',
    item_name: 'Trend formal Collection',
    original_price: 2000,
    current_price: 1200,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 3.5,
        count: 2589,
    },
},

{
    id: '16',
    image:  'images/offers/8.png',
    company: `Levi's`,
    item_name: `Levi's Black Men T-Shirt`,
    original_price: 3000,
    current_price: 1800,
    discount_percentage: 40,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.5,
        count: 3025,
    },
},

{
    id: '17',
    image:  'images/offers/9.png',
    company: 'WoodLand',
    item_name: 'brown causual shoes',
    original_price: 1000,
    current_price: 700,
    discount_percentage: 30,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 2.5,
        count: 1369,
    },
},
{
    id: '18',
    image:  'images/offers/10.png',
    company: 'Allen Solly Women',
    item_name: 'Women Trend Collection',
    original_price: 2000,
    current_price: 1200,
    discount_percentage: 70,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 3.5,
        count: 1659,
    },
},
{
    id: '19',
    image:  'images/offers/11.png',
    company: 'Stunning Footwear',
    item_name: 'Stunning black Collection',
    original_price: 4000,
    current_price: 1600,
    discount_percentage: 60,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 3.5,
        count: 3159,
    },
},
{
    id: '20',
    image:  'images/offers/12.png',
    company: 'Trendiest Fits',
    item_name: 'fits outfit Collection',
    original_price: 5000,
    current_price: 3500,
    discount_percentage: 30,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 3.5,
        count: 2059,
    },
},
];